
Shader "Custom/Wireframe" 
{
	Properties 
	{
		_WireColor("WireColor", Color) = (1,0,0,1)
		_Color("Color", Color) = (1,1,1,1)
	}
	SubShader 
	{

    	Pass 
    	{
			Program "vp" {
// Vertex combos: 1
//   d3d11 - ALU: 1 to 1, TEX: 0 to 0, FLOW: 1 to 1
SubProgram "d3d11 " {
Keywords { }
Bind "vertex" Vertex
Bind "texcoord" TexCoord0
ConstBuffer "UnityPerDraw" 336 // 64 used size, 6 vars
Matrix 0 [glstate_matrix_mvp] 4
BindCB "UnityPerDraw" 0
// 6 instructions, 1 temp regs, 0 temp arrays:
// ALU 1 float, 0 int, 0 uint
// TEX 0 (0 load, 0 comp, 0 bias, 0 grad)
// FLOW 1 static, 0 dynamic
"vs_5_0
eefiecedinkdndjfbjnpndcnhbepmoocokfdamocabaaaaaaaiacaaaaadaaaaaa
cmaaaaaakaaaaaaapiaaaaaaejfdeheogmaaaaaaadaaaaaaaiaaaaaafaaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaafjaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaahaaaaaagaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
apadaaaafaepfdejfeejepeoaaeoepfcenebemaafeeffiedepepfceeaaklklkl
epfdeheofaaaaaaaacaaaaaaaiaaaaaadiaaaaaaaaaaaaaaabaaaaaaadaaaaaa
aaaaaaaaapaaaaaaeeaaaaaaaaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadamaaaa
fdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaklklklfdeieffiaiabaaaa
faaaabaaecaaaaaagkaiaaabfjaaaaaeegiocaaaaaaaaaaaaeaaaaaafpaaaaad
pcbabaaaaaaaaaaafpaaaaaddcbabaaaacaaaaaaghaaaaaepccabaaaaaaaaaaa
abaaaaaagfaaaaaddccabaaaabaaaaaagiaaaaacabaaaaaadiaaaaaipcaabaaa
aaaaaaaafgbfbaaaaaaaaaaaegiocaaaaaaaaaaaabaaaaaadcaaaaakpcaabaaa
aaaaaaaaegiocaaaaaaaaaaaaaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaa
dcaaaaakpcaabaaaaaaaaaaaegiocaaaaaaaaaaaacaaaaaakgbkbaaaaaaaaaaa
egaobaaaaaaaaaaadcaaaaakpccabaaaaaaaaaaaegiocaaaaaaaaaaaadaaaaaa
pgbpbaaaaaaaaaaaegaobaaaaaaaaaaadgaaaaafdccabaaaabaaaaaaegbabaaa
acaaaaaadoaaaaab"
}

}
Program "fp" {
// Fragment combos: 1
//   d3d11 - ALU: 6 to 6, TEX: 0 to 0, FLOW: 1 to 1
SubProgram "d3d11 " {
Keywords { }
ConstBuffer "$Globals" 48 // 48 used size, 3 vars
Vector 16 [_WireColor] 4
Vector 32 [_Color] 4
BindCB "$Globals" 0
// 8 instructions, 2 temp regs, 0 temp arrays:
// ALU 6 float, 0 int, 0 uint
// TEX 0 (0 load, 0 comp, 0 bias, 0 grad)
// FLOW 1 static, 0 dynamic
"ps_5_0
eefiecedhiilmmiomjkfjiclbpgigfghikancooiabaaaaaaomabaaaaadaaaaaa
cmaaaaaajmaaaaaanaaaaaaaejfdeheogiaaaaaaadaaaaaaaiaaaaaafaaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaafmaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadaaaaaafmaaaaaaabaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahahaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaklklklepfdeheo
cmaaaaaaabaaaaaaaiaaaaaacaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaa
apaaaaaafdfgfpfegbhcghgfheaaklklfdeieffibeabaaaafaaaaaaaefaaaaaa
gkaiaaabfjaaaaaeegiocaaaaaaaaaaaadaaaaaagcbaaaadhcbabaaaacaaaaaa
gfaaaaadpccabaaaaaaaaaaagiaaaaacacaaaaaaddaaaaahbcaabaaaaaaaaaaa
ckbabaaaacaaaaaabkbabaaaacaaaaaaddaaaaahbcaabaaaaaaaaaaaakaabaaa
aaaaaaaaakbabaaaacaaaaaadiaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaa
akaabaaaaaaaaaaadiaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaa
aaaaiamabjaaaaafbcaabaaaaaaaaaaaakaabaaaaaaaaaaaaaaaaaakpcaabaaa
abaaaaaaegiocaaaaaaaaaaaabaaaaaaegiocaiaebaaaaaaaaaaaaaaacaaaaaa
dcaaaaakpccabaaaaaaaaaaaagaabaaaaaaaaaaaegaobaaaabaaaaaaegiocaaa
aaaaaaaaacaaaaaadoaaaaab"
}

}
Program "gp" {
// Geometry combos: 1
//   d3d11 - ALU: 19 to 19, TEX: 0 to 0, FLOW: 1 to 1
SubProgram "d3d11 " {
Keywords { }
ConstBuffer "UnityPerCamera" 128 // 112 used size, 8 vars
Vector 96 [_ScreenParams] 4
BindCB "UnityPerCamera" 0
// 36 instructions, 2 temp regs, 0 temp arrays:
// ALU 19 float, 0 int, 0 uint
// TEX 0 (0 load, 0 comp, 0 bias, 0 grad)
// FLOW 1 static, 0 dynamic
"gs_5_0
eefiecednoajlcedcndjohjhhnbmppmfnbkbnfdiabaaaaaaeiafaaaaadaaaaaa
cmaaaaaaieaaaaaaaaabaaaaejfdeheofaaaaaaaacaaaaaaaiaaaaaadiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapapaaaaeeaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfcee
aaklklklepfdehdfheaaaaaaadaaaaaaaiaaaaaaaaaaaaaafmaaaaaaaaaaaaaa
abaaaaaaadaaaaaaaaaaaaaaapaaaaaaaaaaaaaagiaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadamaaaaaaaaaaaagiaaaaaaabaaaaaaaaaaaaaaadaaaaaa
acaaaaaaahaiaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaklklkl
fdeieffieaaeaaaafaaaacaabaabaaaagkaiaaabfjaaaaaeegiocaaaaaaaaaaa
ahaaaaaagbaaaaafpcbacaaaadaaaaaaaaaaaaaaabaaaaaafpaaaaaedcbacaaa
adaaaaaaabaaaaaagiaaaaacacaaaaaafnbiaaabipaaaaadaaaabbaaaaaaaaaa
fmciaaabghaaaaaepccabaaaaaaaaaaaabaaaaaagfaaaaaddccabaaaabaaaaaa
gfaaaaadhccabaaaacaaaaaafoaaaaacadaaaaaadgaaaaagpccabaaaaaaaaaaa
egbocaaaaaaaaaaaaaaaaaaadgaaaaagdccabaaaabaaaaaaegbacaaaaaaaaaaa
abaaaaaadiaaaaaldcaabaaaaaaaaaaaegiacaaaaaaaaaaaagaaaaaaaceaaaaa
aaaaaadpaaaaaadpaaaaaaaaaaaaaaaadiaaaaaimcaabaaaaaaaaaaaagaebaaa
aaaaaaaaagbecaaaabaaaaaaaaaaaaaaaoaaaaaimcaabaaaaaaaaaaakgaobaaa
aaaaaaaapgbpcaaaabaaaaaaaaaaaaaadiaaaaaidcaabaaaabaaaaaaegaabaaa
aaaaaaaaegbacaaaacaaaaaaaaaaaaaadiaaaaaidcaabaaaaaaaaaaaegaabaaa
aaaaaaaaegbacaaaaaaaaaaaaaaaaaaaaoaaaaaidcaabaaaaaaaaaaaegaabaaa
aaaaaaaapgbpcaaaaaaaaaaaaaaaaaaaaoaaaaaidcaabaaaabaaaaaaegaabaaa
abaaaaaapgbpcaaaacaaaaaaaaaaaaaaaaaaaaaimcaabaaaabaaaaaakgaobaia
ebaaaaaaaaaaaaaaagaebaaaabaaaaaaaaaaaaaimcaabaaaaaaaaaaaagaebaia
ebaaaaaaaaaaaaaakgaobaaaaaaaaaaaaaaaaaaidcaabaaaaaaaaaaaegaabaia
ebaaaaaaaaaaaaaaegaabaaaabaaaaaaapaaaaahbcaabaaaabaaaaaaogakbaaa
abaaaaaaogakbaaaabaaaaaaelaaaaafbcaabaaaabaaaaaaakaabaaaabaaaaaa
diaaaaahccaabaaaabaaaaaackaabaaaaaaaaaaabkaabaaaaaaaaaaadcaaaaak
ccaabaaaabaaaaaaakaabaaaaaaaaaaadkaabaaaaaaaaaaabkaabaiaebaaaaaa
abaaaaaaapaaaaahbcaabaaaaaaaaaaaegaabaaaaaaaaaaaegaabaaaaaaaaaaa
elaaaaafbcaabaaaaaaaaaaaakaabaaaaaaaaaaaapaaaaahccaabaaaaaaaaaaa
ogakbaaaaaaaaaaaogakbaaaaaaaaaaaelaaaaafccaabaaaaaaaaaaabkaabaaa
aaaaaaaaaoaaaaaidcaabaaaaaaaaaaafgafbaiaibaaaaaaabaaaaaaegaabaaa
aaaaaaaaaoaaaaaiecaabaaaaaaaaaaabkaabaiaibaaaaaaabaaaaaaakaabaaa
abaaaaaadgaaaaafbccabaaaacaaaaaackaabaaaaaaaaaaadgaaaaaigccabaaa
acaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaahfaaaaadaaaabbaa
aaaaaaaadgaaaaagpccabaaaaaaaaaaaegbocaaaabaaaaaaaaaaaaaadgaaaaag
dccabaaaabaaaaaaegbacaaaabaaaaaaabaaaaaadgaaaaaifccabaaaacaaaaaa
aceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadgaaaaafcccabaaaacaaaaaa
akaabaaaaaaaaaaahfaaaaadaaaabbaaaaaaaaaadgaaaaagpccabaaaaaaaaaaa
egbocaaaacaaaaaaaaaaaaaadgaaaaagdccabaaaabaaaaaaegbacaaaacaaaaaa
abaaaaaadgaaaaaidccabaaaacaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaadgaaaaafeccabaaaacaaaaaabkaabaaaaaaaaaaahfaaaaadaaaabbaa
aaaaaaaadoaaaaab"
}

}

#LINE 90


    	}
	}
}